# Prevent hydra from taking over working dir
hydra:
  run:
    dir: .
  output_subdir: null

hydra/job_logging: disabled
hydra/hydra_logging: disabled

defaults:
  - env: default.yml

neptune:
  offline: false
  key: "secret"
  run_name: "experiment"
  run_id: null

training:
  random_seed: 20302
  batch_size: 32
  lr: 0.0001
  epochs: 80
  backbone: "resnet50"
  checkpoint: null

  sync_rate: 100
  update_interval: 1

  envs_per_worker: 1

  loss:
    gamma: 0.95

valdation:
  every: 500

dataset: simple

data_path: /Users/Emanuel/Documents/Studium/Master/Masterarbeit/data/600_3_signs_3_words

eval_data_path: null

eval_gt_file: simple_gt.zip

assessor_data_path: null

assessor_model_checkpoint: null

log_dir: /Users/Emanuel/ray_results

restore: null

custom_model: true

framestacking: false
