hydra:
  run:
    dir: .
  output_subdir: null

hydra/job_logging: disabled
hydra/hydra_logging: disabled

defaults:
  - env: default.yml

neptune:
  offline: true
  key: "secret"
  run_name: "experiment"

training:
  batch_size: 16
  lr: 0.0001
  epochs: 50
  backbone: "resnet50"
  checkpoint: null

  sync_rate: 100
  update_interval: 1

  loss:
    gamma: 0.95

valdation:
  every: 500

dataset: sign