hydra:
  run:
    dir: .
  output_subdir: null

hydra/job_logging: disabled
hydra/hydra_logging: disabled

defaults:
  - env: default.yml

apex:
  num_actors: 4
  learner_device: cuda
  publish_params_interval: 10

neptune:
  offline: false
  key: "secret"
  run_name: "experiment"
  run_id: null

training:
  batch_size: 512
  lr: 0.0001
  epochs: 80
  backbone: "resnet50"
  checkpoint: null

  sync_rate: 100
  update_interval: 1

  envs_per_worker: 10

  loss:
    gamma: 0.95

valdation:
  every: 500

dataset: simple

data_path: /Users/Emanuel/Documents/Studium/Master/Masterarbeit/data/dataset-generator

log_dir: /Users/Emanuel/ray_results