# @package _group_
random_seed: 20301

steps_per_image: 100

max_reward: 200

full_playout: false

premasking: true

termination: false

framestacking_mode: null

eval_full_playout: false

bbox_scaling_width: 0

bbox_scaling_height: 0