# @package _group_
random_seed: 20301

steps_per_image: 100

max_reward: 200

full_playout: false

premasking: true

premasking_decay: null

termination: false

framestacking_mode: null

bbox_scaling_width: 0

bbox_scaling_height: 0