# @package _group_
random_seed: 20301
steps_per_image: 200
steps_per_epoch: 1000

replay_buffer:
  size: 1000
  warm_up_steps: 1000

epsilon:
  start: 1
  end: 0.1
  decay_steps: 100000

max_reward: 200

full_playout: false

premasking: false

termination: false

intermediate_reward: false

upper_confidence_bound: false